# Generated by Django 2.2.5 on 2019-10-16 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlidingScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale', models.CharField(max_length=1)),
                ('sf1', models.IntegerField()),
                ('sf2', models.IntegerField()),
                ('sf3', models.IntegerField()),
                ('sf4', models.IntegerField()),
                ('sf5', models.IntegerField()),
                ('sf6', models.IntegerField()),
                ('sf7', models.IntegerField()),
                ('sf8', models.IntegerField()),
            ],
        ),
    ]
