# Generated by Django 2.2.5 on 2019-10-16 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slidingscale',
            old_name='sf1',
            new_name='fs_1',
        ),
        migrations.RenameField(
            model_name='slidingscale',
            old_name='sf2',
            new_name='fs_2',
        ),
        migrations.RenameField(
            model_name='slidingscale',
            old_name='sf3',
            new_name='fs_3',
        ),
        migrations.RenameField(
            model_name='slidingscale',
            old_name='sf4',
            new_name='fs_4',
        ),
        migrations.RenameField(
            model_name='slidingscale',
            old_name='sf5',
            new_name='fs_5',
        ),
        migrations.RenameField(
            model_name='slidingscale',
            old_name='sf6',
            new_name='fs_6',
        ),
        migrations.RenameField(
            model_name='slidingscale',
            old_name='sf7',
            new_name='fs_7',
        ),
        migrations.RenameField(
            model_name='slidingscale',
            old_name='sf8',
            new_name='fs_8',
        ),
    ]
